<?php
// Generated by zData.php
$mytVar = array(
   "DefaultEffort" => 1,
   "DefaultIdProject" => 1,
   "DefaultPriority" => 1,
   "NextIdProject" => 1,
   "NextIdTask" => 1,
   "IsDisplayingProjectList" => true,
   "IsVisibleArchive" => true,
   "IsVisibleDocumentation" => true,
   "IsVisibleRelease" => true,
   "IsVisibleTesting" => true,
   "IsVisibleWork" => true,
   "SortOrderProject" => "i",
   "SortOrderTask" => "i");
